{% set name = "mbedtls" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Mbed-TLS/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 377a09cf8eb81b5fb2707045e5522d5489d3309fed5006c9874e60558fc81d10

build:
  number: 0
  run_exports:
    # mbedtls has an ABI versions that seems to change per minor release:
    # https://github.com/Mbed-TLS/mbedtls/blob/f3720c7ca9f0f7dff39a38c7d779d493e4acee4e/library/CMakeLists.txt#L179C1-L180C1
    - {{ pin_subpackage('mbedtls', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/mbedtls/private/md5.h             # [unix]
    - test -f ${PREFIX}/lib/libmbedtls${SHLIB_EXT}                # [unix]
    - test -f ${PREFIX}/lib/libmbedcrypto${SHLIB_EXT}             # [unix]
    - if not exist %LIBRARY_INC%\\mbedtls\\private\\md5.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libmbedcrypto.dll exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\libmbedcrypto.lib exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\mbedtls.dll exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\mbedtls.lib exit 1              # [win]

about:
  home: https://www.trustedfirmware.org/projects/mbed-tls
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library
  description: |
    An open source, portable, easy to use, readable and flexible TLS library, 
    and reference implementation of the PSA Cryptography API.
  dev_url: https://github.com/Mbed-TLS/mbedtls
  doc_url: https://mbed-tls.readthedocs.io

extra:
  recipe-maintainers:
    - izahn
    - carlodri
    - xhochy
